spring.application.name=analysis-service
server.port=8082

# Vault Configuration
spring.config.import=vault://
spring.cloud.vault.uri=http://127.0.0.1:8200
spring.cloud.vault.token=root
spring.cloud.vault.scheme=http
spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=secret

# Spring AI / Ollama Configuration
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=gemma:2b
spring.ai.ollama.chat.options.temperature=0.0

# Logging
logging.file.name=logs/analysis-service.log
logging.level.org.springframework.ai=DEBUG