spring.application.name=trading-service
server.port=8083

# Vault Configuration
spring.config.import=vault://
spring.cloud.vault.uri=http://127.0.0.1:8200
spring.cloud.vault.token=root
spring.cloud.vault.scheme=http
spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=secret

# Database Configuration (Username and Password are fetched from Vault)
spring.datasource.url=jdbc:postgresql://localhost:5433/trading_app_db
# spring.datasource.username=trading_user
# spring.datasource.password=trading_password
spring.jpa.hibernate.ddl-auto=update

# Logging Configuration
logging.file.name=logs/trading-service.log
logging.level.org.apache.catalina=INFO
logging.level.com.trading.trading_service=DEBUG
