spring.application.name=api-gateway
server.port=8080
spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.cloud.gateway.mvc.routes[0].id=health_route
spring.cloud.gateway.mvc.routes[0].uri=no://op
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/health
spring.cloud.gateway.mvc.routes[0].filters[0]=SetStatus=200

spring.cloud.gateway.mvc.routes[1].id=account_service_route
spring.cloud.gateway.mvc.routes[1].uri=http://localhost:8081
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/accounts/**

# Logging Configuration
logging.file.name=logs/api-gateway.log
logging.level.org.apache.catalina=INFO
logging.level.org.apache.coyote=INFO
