spring.application.name=account-service
server.port=8081

# Vault Configuration
spring.config.import=vault://
spring.cloud.vault.uri=http://127.0.0.1:8200
spring.cloud.vault.token=root
spring.cloud.vault.scheme=http
spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=secret

# Database Configuration (Username and Password are automatically fetched from Vault!)
spring.datasource.url=jdbc:postgresql://localhost:5432/trading_app_db
spring.jpa.hibernate.ddl-auto=update

# Logging Configuration
logging.file.name=logs/account-service.log
logging.level.org.apache.catalina=INFO
logging.level.org.apache.coyote=INFO